version: '3'
services:
  #PHP Service
  php8.1:
    build:
      context: ./dockerfile
      dockerfile: php8.1
    container_name: php8.1
    restart: unless-stopped
    tty: true
    working_dir: /var/www/php/8.1
    volumes:
      - ./php/8.1:/var/www/php/8.1
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php:/var/www/php
      - ./nginx/conf.d/enable:/etc/nginx/conf.d/
      - ./nginx/ssl_key/server.crt:/etc/nginx/server.crt
      - ./nginx/ssl_key/server.key:/etc/nginx/server.key
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
