version: '3'
services:
  #PHP Service
  php8.2:
    build:
      context: ./dockerfile
      dockerfile: php8.2
    container_name: php8.2
    restart: unless-stopped
    tty: true
    working_dir: /home/php/8.2
    volumes:
      - ./php/8.2:/home/php/8.2
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php:/home/php
      - ./nginx/conf.d/enable:/etc/nginx/conf.d/
      - ./nginx/ssl_key/server.crt:/etc/nginx/server.crt
      - ./nginx/ssl_key/server.key:/etc/nginx/server.key
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
