version: '2'
services:
  mongodb:
    image: mongo:4.4.14
    container_name: mongodb_4.4.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
